apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tektutor-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: no-provisioning 
parameters:
  server: 192.168.1.108 
  path: /mnt/nfs/storageclass
  readOnly: "false"
