apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-jegan # Replace 'jegan' with your name
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: tektutor-nfs 
  resources:
    requests:
      storage: 100Mi
